name: Upsert Commands

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ steps.versions.outputs.deno }}

      - name: Upsert commands
        run: deno task run tasks/upsert_global_commands_task.ts
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
